### ISSUE TITLE
Recalculate sha1 value

### ISSUE THREAD

**Issue by saitho** [ElementareTeilchen/unduplicator#6]
When deduplicating `sys_file` entries, the sha1 field should be recalculated and saved to the remaining `sys_file` record, in order to make sure the entry is always correct.

**Comment by sypets** [comment]
Why should the sha1 value be recalculated? The file is not changed.

Probably, the duplicates may occur because of the wrong hash. But we don't know this. It is one of the possible reasons. 
Maybe in this case it is better to use existing functionality:

For example, you could recommend to run the file indexer (see scheduler) before and after running unduplicator. 

Related: #7

**Comment by saitho** [comment]
I'm currently investigating an issue with duplicate sys_file entries. For some reason the sha1 values are different.
It looked like the second entry's sha1 value was correct. If File Indexer updates the sha1 value, that's also fine and should be done as you said.

Closing for now :)

**Comment by saitho** [comment]
> It looked like the second entry's sha1 value was correct.

I cleared up my confusion. I thought the sys_file with the lower UID is considered the original, but in fact it's the higher UID. Everything fine then.

**Comment by sypets** [comment]
@saitho While you are at it - can you also look at and test my PR? #3 :wink:
